// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwriugwdamvctevwrvew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cml1Z3dkYW12Y3RldndydmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODMzMzUsImV4cCI6MjA3MjU1OTMzNX0.cR4sLpeYa-o7sbhyCYAuAU6gjn7BBq-cEnlStTxToV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});